# Generated by Django 3.2.9 on 2021-12-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_expired', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('max_group_num', models.IntegerField(default=5)),
                ('max_team_member_num', models.IntegerField(default=5)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(to='piggy.Student')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.project')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.plan')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.team')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.teacher'),
        ),
    ]
