# Generated by Django 3.2.9 on 2021-11-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0002_rename_group_teamwish_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_expired', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.plan'),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piggy.plan'),
        ),
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
