# Generated by Django 3.2.8 on 2021-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0004_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
